
	-- SIMPLE 'MERGE'
	
	MERGE INTO 
		DESTINATION_TABLE DEST
	USING
		SOURCE_TABLE SRC
	ON (
		DEST.ID = SRC.ID
	)
	
	WHEN MATCHED THEN
		UPDATE SET
			FIRST_COLUMN_VALUE = SRC.FIRST_COLUMN_VALUE
			SECOND_COLUMN_VALUE = SRC.SECOND_COLUMN_VALUE
			THIRD_COLUMN_VALUE = SRC.THIRD_COLUMN_VALUE
	WHEN NOT MATCHED THEN
		INSERT (
			FIRST_COLUMN_VALUE,
			SECOND_COLUMN_VALUE,
			THIRD_COLUMN_VALUE
		)
		VALUES (
			SRC.FIRST_COLUMN_VALUE,
			SRC.SECOND_COLUMN_VALUE,
			SRC.THIRD_COLUMN_VALUE
		)
		
	-- MERGE USING A 'SELECT' STATEMENT
	
	MERGE INTO 
		DESTINATION_TABLE DEST
	USING (
		SELECT 
			FIRST_COLUMN_VALUE,
			SECOND_COLUMN_VALUE,
			THIRD_COLUMN_VALUE
		FROM
			SOURCE_TABLE
		WHERE
			THIRD_COLUMN_VALUE = "EXPECTED_FILTER_VALUE"
	)
		
	ON (
		DEST.ID = SRC.ID
	)
	
	WHEN MATCHED THEN
		UPDATE SET
			FIRST_COLUMN_VALUE = SRC.FIRST_COLUMN_VALUE
			SECOND_COLUMN_VALUE = SRC.SECOND_COLUMN_VALUE
			THIRD_COLUMN_VALUE = SRC.THIRD_COLUMN_VALUE
	WHEN NOT MATCHED THEN
		INSERT (
			FIRST_COLUMN_VALUE,
			SECOND_COLUMN_VALUE,
			THIRD_COLUMN_VALUE
		)
		VALUES (
			SRC.FIRST_COLUMN_VALUE,
			SRC.SECOND_COLUMN_VALUE,
			SRC.THIRD_COLUMN_VALUE
		)
	
	-- MERGE USING AN 'WHERE' STATEMENT ON 'MATCHED' AND 'NOT MATCHED' STATEMENT
		-- FOR A ROW TO BE UPDATED OR INSERTED
			-- IT HAS TO BOTH MATCHES THE 'ON' STATEMENT CRITERIA AND THE 'WHERE' STATEMENT CRITERIA
	
	MERGE INTO 
		DESTINATION_TABLE DEST
	USING
		SOURCE_TABLE SRC
	ON (
		DEST.ID = SRC.ID
	)
	
	WHEN MATCHED THEN
		UPDATE SET
			FIRST_COLUMN_VALUE = SRC.FIRST_COLUMN_VALUE
			SECOND_COLUMN_VALUE = SRC.SECOND_COLUMN_VALUE
			THIRD_COLUMN_VALUE = SRC.THIRD_COLUMN_VALUE
		WHERE
			SRC.THIRD_COLUMN_VALUE = "UPDATE_FILTER_VALUE"
	WHEN NOT MATCHED THEN
		INSERT (
			FIRST_COLUMN_VALUE,
			SECOND_COLUMN_VALUE,
			THIRD_COLUMN_VALUE
		)
		VALUES (
			SRC.FIRST_COLUMN_VALUE,
			SRC.SECOND_COLUMN_VALUE,
			SRC.THIRD_COLUMN_VALUE
		)
		WHERE
			SRC.THIRD_COLUMN_VALUE = "INSERT_FILTER_VALUE"
	
	-- MERGE USING ONLY 'MATCHED' STATEMENT
		-- ONLY EXISTING ROWS WILL BE UPDATED
	
	MERGE INTO 
		DESTINATION_TABLE DEST
	USING
		SOURCE_TABLE SRC
	ON (
		DEST.ID = SRC.ID
	)
	
	WHEN MATCHED THEN
		UPDATE SET
			FIRST_COLUMN_VALUE = SRC.FIRST_COLUMN_VALUE
			SECOND_COLUMN_VALUE = SRC.SECOND_COLUMN_VALUE
			THIRD_COLUMN_VALUE = SRC.THIRD_COLUMN_VALUE
		
	-- MERGE USING ONLY 'NOT MATCHED' STATEMENT
		-- WILL BE USED TO INSERT ONLY THE MISSING ROWS
	
	MERGE INTO 
		DESTINATION_TABLE DEST
	USING
		SOURCE_TABLE SRC
	ON (
		DEST.ID = SRC.ID
	)
	
	WHEN NOT MATCHED THEN
		INSERT (
			FIRST_COLUMN_VALUE,
			SECOND_COLUMN_VALUE,
			THIRD_COLUMN_VALUE
		)
		VALUES (
			SRC.FIRST_COLUMN_VALUE,
			SRC.SECOND_COLUMN_VALUE,
			SRC.THIRD_COLUMN_VALUE
		)
	
	-- MERGE USING A 'DELETE' CLAUSE STATEMENT
	
	MERGE INTO 
		DESTINATION_TABLE DEST
	USING
		SOURCE_TABLE SRC
	ON (
		DEST.ID = SRC.ID
	)
	
	WHEN MATCHED THEN
		UPDATE SET
			FIRST_COLUMN_VALUE = SRC.FIRST_COLUMN_VALUE
			SECOND_COLUMN_VALUE = SRC.SECOND_COLUMN_VALUE
			THIRD_COLUMN_VALUE = SRC.THIRD_COLUMN_VALUE
		DELETE
			WHERE
				DEST.EXAMPLE_COLUMN = "VALUE_TO_DELETE"
