
	MERGE INTO 
		DESTINATION_TABLE DEST
	USING
		SOURCE_TABLE SRC
	ON
		DEST.ID = SRC.ID
	
	WHEN MATCHED THEN
		UPDATE SET
			FIRST_COLUMN_VALUE = SRC.FIRST_COLUMN_VALUE
			SECOND_COLUMN_VALUE = SRC.SECOND_COLUMN_VALUE
			THIRD_COLUMN_VALUE = SRC.THIRD_COLUMN_VALUE
	WHEN NOT MATCHED THEN
		INSERT (
			FIRST_COLUMN_VALUE,
			SECOND_COLUMN_VALUE,
			THIRD_COLUMN_VALUE
		)
		VALUES (
			SRC.FIRST_COLUMN_VALUE,
			SRC.SECOND_COLUMN_VALUE,
			SRC.THIRD_COLUMN_VALUE
		)
